### ISSUE TITLE
Link to site on README doesn't work.

### ISSUE THREAD

**Issue by dragonfire2314** [pilcrowonpaper/reddit-client#60]
### Description
The link for the site in the read me takes me to https://github.com/pilcrowOnPaper/arctic/blob/main/arctic-reddit.vercel.app instead of  https://arctic-reddit.vercel.app/ 

Doing this fixed it for me. 

### Possible Fix
``` markdown
[arctic-reddit.vercel.app](https://arctic-reddit.vercel.app/)

__Important Note__: You cannot use www.reddit.com and [arctic-reddit.vercel.app](https://arctic-reddit.vercel.app/) interchangeably.
```

### Importance
low

**Comment by pilcrowonpaper** [comment]
Sorry for the late reply! Thanks for bringing it up and it was fixed with the recent commit.
